server:
    port: 8080
    tomcat:
        accesslog:
          enabled: true
          pattern: common
        background-processor-delay: 30
        basedir: ../tmp
        uri-encoding: UTF-8
spring:
    dao:
        exceptiontranslation:
            enabled: true
    data:
        jpa:
            repositories:
                enabled: true
    datasource:
        continue-on-error: false
        data: data.sql
        driverClassName: com.mysql.cj.jdbc.Driver
        name: datasource
        platform: mysql
        schema: schema.sql
        separator: ;
        sql-script-encoding: utf-8
        url: jdbc:mysql://localhost:3306/ms?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    thymeleaf:
        cache: false
        check-template-location: true
        content-type: text/html
        encoding: UTF-8
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html
    mail:
        host: smtp.qq.com
        username: 205002518@qq.com
        password: tksidlhgnbuqbjdf
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true

